# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  title: Brain & Language Cognition Lab
# Uncomment the lines below to configure your website in a second language.
#zh:
  languageCode: zh
  contentDir: content/zh
  title: 脑与语言认知实验室
  params:
    description: 脑与语言认知实验室致力于揭示第二语言学习规律以及双语加工的认知与神经机制。当前实验室的主要研究方向包括：1）双语加工的心理和脑机制；2）语言学习的认知神经机制；3）语言对思维、决策等社会认知活动的影响机制。
  menu:
    main:
      - name: 传
        url: '#about'
        weight: 1



########################################################################################
# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
#[en]
#  languageCode = "en-us"
#   contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
#   title = "Brain & Language Cognition Lab"
   
# Uncomment the lines below to configure your website in a second language.
#[zh]
#  languageCode = "zh"
#  contentDir = "content/zh"
  #title = "脑与语言认知实验室"
#  [zh.params]
#    description = "脑与语言认知实验室致力于揭示第二语言学习规律以及双语加工的认知与神经机制。当前实验室的主要研究方向包括：1）双语加工的心理和脑机制；2）语言学习的认知神经机制；3）语言对思维、决策等社会认知活动的影响机制。"
#  [[zh.menu.main]]
#    name = "Wo"
#    url = "#about"
#    weight = 1
